resolver: ghc-9.2
packages:
    - .
    - sandbox
extra-deps:
    - extra-1.7.8
    - clock-0.8
    - split-0.2.3.4
    - criterion-1.5.13.0
    - Glob-0.10.2
    - aeson-2.0.3.0
    - ansi-wl-pprint-0.6.9
    - base-compat-batteries-0.12.1
    - binary-orphans-1.0.2
    - cassava-0.5.2.0
    - code-page-0.2.1
    - criterion-measurement-0.1.3.0
    - js-chart-2.9.4.1
    - microstache-1.0.2
    - mwc-random-0.15.0.2
    - optparse-applicative-0.17.0.0
    - statistics-0.16.0.1
    - transformers-compat-0.7.1
    - vector-0.12.3.1
    - vector-algorithms-0.8.0.4
    - OneTuple-0.3.1
    - Only-0.1
    - QuickCheck-2.14.2
    - ansi-terminal-0.11.1
    - async-2.2.4
    - attoparsec-0.14.4
    - base-compat-0.12.1
    - data-default-class-0.1.2.0
    - data-fix-0.3.2
    - dense-linear-algebra-0.1.0.0
    - dlist-1.0
    - hashable-1.4.0.2
    - indexed-traversable-0.1.2
    - math-functions-0.3.4.2
    - monad-par-0.3.5
    - primitive-0.7.3.0
    - random-1.2.1
    - scientific-0.3.7.0
    - semialign-1.2.0.1
    - strict-0.4.0.1
    - tagged-0.8.6.1
    - text-short-0.1.5
    - th-abstraction-0.4.3.0
    - these-1.1.1.1
    - time-compat-1.9.6.1
    - unordered-containers-0.2.16.0
    - uuid-types-1.0.5
    - vector-binary-instances-0.2.5.2
    - vector-th-unbox-0.2.2
    - witherable-0.4.2
    - abstract-deque-0.3
    - abstract-par-0.3.3
    - assoc-1.0.2
    - base-orphans-0.8.6
    - colour-2.3.6
    - indexed-traversable-instances-0.1.1
    - integer-logarithms-1.0.3.1
    - monad-par-extras-0.3.3
    - parallel-3.2.2.0
    - semigroupoids-5.3.7
    - splitmix-0.1.0.4
    - bifunctors-5.5.11
    - cereal-0.5.8.2
    - comonad-5.0.8
    - contravariant-1.5.5
    - distributive-0.6.2.1
    - StateVar-1.2.2

ghc-options:
    "$everything": -Wall
system-ghc: true
allow-newer: true
